# Generated by Django 5.1.2 on 2024-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('media_type', models.CharField(max_length=16)),
                ('copyright', models.BooleanField(null=True)),
                ('download_count', models.IntegerField()),
                ('subjects_json', models.JSONField()),
                ('bookshelves_json', models.JSONField()),
                ('formats_json', models.JSONField()),
                ('languages', models.ManyToManyField(to='books.language')),
                ('authors', models.ManyToManyField(to='books.person')),
                ('translators', models.ManyToManyField(related_name='books_translated', to='books.person')),
            ],
        ),
    ]
